### ISSUE TITLE
I can't install opencv-dynamic 

### ISSUE THREAD

**Issue by ljfantin** [Legoless/OpenCV-Dynamic#2]
@Legoless sorry, but i can't install OpenCV-Dynamic (3.2.1), I get the next error when I run pod install

`Fetched in submodule path 'opencv', but it did not contain beec247c4e0693b6961cd1bb164824db4abf1ad1. Direct fetching of that commit failed.`

**Comment by Legoless** [comment]
This is because the submodule points to my opencv fork, because changes were not merged into the master repository. Latest version works, but I will soon release a new version that will use the master [opencv](https://github.com/opencv/opencv) repository to avoid errors like these in the future. I will keep this issue open until that is done.

**Comment by Legoless** [comment]
I've pushed version 3.2.3, which uses main repository instead of my fork. Closing this for now.
